---
- name: Make gitlab proj
  hosts: all
  gather_facts: False
  tasks:
  - name: Make gitlab proj 
    ping:
      data: pong from Ansible
  - name: Add access rights 
    ping:
      data: pong from Ansible
