---
- name: Make jfrog repository
  hosts: all
  gather_facts: False
  tasks:
  - name: Make jfrog repository 
    ping:
      data: pong from Ansible
  - name: Set access rights 
    ping:
      data: pong from Ansible
