- name: Unlock my user
  hosts: all
  gather_facts: False
  tasks:
  - name: is the domain responsive
    win_ping:
  - name: Unlock this users account
    community.windows.win_domain_user:
      name: "{{ user_name }}"
      account_locked: no
